version: "3.8"

services:
  backend:
    build: ./chatBackend
    ports:
      - "8080:8080"
    networks:
      - mern_network
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development  

  frontend:
    build: ./chatFrontend
    ports:
      - "5173:5173"
    networks:
      - mern_network
    environment:
      - CUSTOM_FILE_WATCHER=true
    # volumes:
    #   - .:/app/frontend:delegated
    #   - /app/frontend/node_modules
    volumes:
      - ./chatFrontend:/app
      - /app/node_modules 

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  

networks:
  mern_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
